-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    -- 1세대: 부모가 없는 루트
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 자식으로 내려가며 세대 + 1
    SELECT C.ID, C.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA C
    JOIN GEN G
      ON C.PARENT_ID = G.ID
)

SELECT
    COUNT(*) AS COUNT,
    GENERATION
FROM GEN G
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA C
    WHERE C.PARENT_ID = G.ID   -- G.ID가 부모로 한 번이라도 나오면 자식이 있음
)
GROUP BY GENERATION
ORDER BY GENERATION;